apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/rafaelalvesbsb/GitOps-LAB-Kubernetes-Observabilidade.git
    targetRevision: main
    path: infra/overlays/dev/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
