apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/rafaelalvesbsb/GitOps-LAB-Kubernetes-Observabilidade.git
    targetRevision: main
    path: infra/overlays/dev/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
